default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Hachi88%
  host: localhost

development:
  <<: *default
  database: todo_nextjs_rails_development

test:
  <<: *default
  database: todo_nextjs_rails_test

production:
  <<: *default
  database: todo_nextjs_rails_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
